language: node_js

cache:
  yarn: true
  directories:
    - node_modules

node_js: stable

matrix:
  fast_finish: true

sudo: false

branches:
  except:
    - gh-pages
    - /analysis-.*/

install:
  - npm install -g codecov
  - yarn install

script:
  - yarn lint
  - yarn test
  - yarn build
  - yarn build:demo

after_success:
  - codecov

deploy:
  - provider: pages # <https://docs.travis-ci.com/user/deployment/pages/>
    keep_history: true
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist-demo
    on:
      #tags: true
      #branch: master
      branch: dev

  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    draft: true
    on:
      #tags: true
      #branch: master
      branch: dev

  - provider: npm # <https://docs.travis-ci.com/user/deployment/npm/>
    email: $NPM_DEPLOY_EMAIL
    api_key: $NPM_DEPLOY_TOKEN
    skip_cleanup: true
    on:
      #tags: true
      #branch: master
      branch: dev
